---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: "[9, 9, 9, 9, {9: 18}]"
  checked: false
- value: "'llamado'"
  checked: false
- value: "'mi_lista'"
  checked: true
- value: "[ 9, 9, {9: 18}]"
  checked: false
name: Más funciones
