---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "[9, 9, 9, 9, {9: 18}]"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "'llamado'"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "'mi_lista'"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "[ 9, 9, {9: 18}]"
  checked: false
name: Más funciones
